### ISSUE TITLE
Locations endpoint data doesn't match actual json properties

### ISSUE THREAD

**Issue by nvreez** [rjh622/datavis-airpollution#7]
The location data returned from `/api/locations` uses underscores while the `/api/pollutionRecords` JSON uses camelCase in its properties. The goal for `/api/locations` is to serve as a guide for the JSON data and should use the same style.

**Comment by nvreez** [comment]
As a bonus, it would be nice to have both the property names as used in the JSON as well as pretty names, but I'm not sure if you have those? So "Kwun Tong".

**Comment by rjh622** [comment]
I've just pushed several changes which:

1. Add 'pretty' location names in the response of the location endpoint.
2. Use underscores in all references of a location. In the past, the variable name was used in places by Spring, which by convention was camelCase.

**Comment by rjh622** [comment]
One final comment: going forward please use the following underscore-based endpoint for pollution records instead of the previous camelCase endpoint.

GET api/pollution-records

I've also updated the documentation to refer to this endpoint. The previous endpoint seems to be still working by Spring for some reason but it is hereforth deprecated!
